def remote = [:]
pipeline {
    agent any
    parameters {
        booleanParam(
            name: 'RUN_TESTS',
            defaultValue: true,
            description: 'Run auto tests'
        )
        string(
            name: 'IMAGE_TAG',
            defaultValue: 'latest'
        )
    }

    environment {
        REPO = 'anestesia01/counter'
        DOCKER_TOKEN = credentials('docker-token')
        HOST = '18.217.86.128'
        GIT_URL = 'git@github.com:AnastasiyaGapochkina01/dos-31.git'
        BASE_DIR = 'less_28'
        PRJ_DIR = '/var/www/counter'
        DOCKER_USER = 'anestesia01'
    }

    stages {
        stage('Configure credentials') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-key', keyFileVariable: 'private_key', usernameVariable: 'username')]) {
                    script {
                        remote.name = "${env.HOST}"
                        remote.host = "${env.HOST}"
                        remote.user = "$username"
                        remote.identity = readFile "$private_key"
                        remote.allowAnyHosts = true
                    }
                }
            }
        }

        stage('Checkout repo') {
            steps {
                git branch: 'main', url: "${env.GIT_URL}", credentialsId: 'jenkins-key'
            }
        }

        stage('Run tests') {
            when {
                expression { params.RUN_TESTS == true }
            }
            steps {
                pytest ${env.BASE_DIR} 
            }
        }

        stage('Build docker image') {
            steps {
                script {
                    sh """
                        docker build -t ${env.REPO}:${params.IMAGE_TAG} ${env.BASE_DIR}
                    """
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    sh """
                        docker login -u ${env.DOCKER_USER} -p ${env.DOCKER_TOKEN} 
                        docker push ${env.REPO}:${params.IMAGE_TAG}
                        docker logout
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sshCommand remote: remote, command: """
                        docker pull ${env.REPO}:${params.IMAGE_TAG}
                        cd ${env.PRJ_DIR}
                        export APP_IMAGE=${env.REPO}:${params.IMAGE_TAG}
                        envsubst < compose.tmpl > compose.yaml
                        docker compose up -d
                    """
                }
            }
        }
    }
}
